services:
  cn1:
    image: ghcr.io/gnosisguild/ciphernode:latest
    volumes:
      - ./.deploy/cn1.yaml:/home/ciphernode/.config/enclave/config.yaml:ro
      - cn1-data:/home/ciphernode/.local/share/enclave
    secrets:
      - source: secrets_cn1
        target: secrets.json
    environment:
      RUST_LOG: "info"
      AGGREGATOR: "false"
    ports:
      - target: 9091
        published: 9091
        protocol: udp
        mode: host
   deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
    networks:
      - global-network


  cn2:
    image: ghcr.io/gnosisguild/ciphernode:latest
    depends_on:
      - cn1
    volumes:
      - ./.deploy/cn2.yaml:/home/ciphernode/.config/enclave/config.yaml:ro
      - cn2-data:/home/ciphernode/.local/share/enclave
    secrets:
      - source: secrets_cn2
        target: secrets.json
    environment:
      RUST_LOG: "info"
      AGGREGATOR: "false"
    ports:
      - target: 9092
        published: 9092
        protocol: udp
        mode: host
   deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
    networks:
      - global-network

  cn3:
    image: ghcr.io/gnosisguild/ciphernode:latest
    depends_on:
      - cn1
    volumes:
      - ./.deploy/cn3.yaml:/home/ciphernode/.config/enclave/config.yaml:ro
      - cn3-data:/home/ciphernode/.local/share/enclave
    secrets:
      - source: secrets_cn3
        target: secrets.json
    environment:
      RUST_LOG: "info"
      AGGREGATOR: "false"
    ports:
      - target: 9093
        published: 9093
        protocol: udp
        mode: host
   deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
    networks:
      - global-network


  aggregator:
    image: ghcr.io/gnosisguild/ciphernode:latest
    depends_on:
      - cn1
    volumes:
      - ./.deploy/agg.yaml:/home/ciphernode/.config/enclave/config.yaml:ro
      - agg-data:/home/ciphernode/.local/share/enclave
    secrets:
      - source: secrets_agg
        target: secrets.json
    environment:
      RUST_LOG: "info"
      AGGREGATOR: "true"
    ports:
      - target: 9094
        published: 9094
        protocol: udp
        mode: host
   deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
    networks:
      - global-network

secrets:
  secrets_cn1:
    file: .deploy/cn1.secrets.json
  secrets_cn2:
    file: .deploy/cn2.secrets.json
  secrets_cn3:
    file: .deploy/cn3.secrets.json
  secrets_agg:
    file: .deploy/agg.secrets.json   

volumes:
  cn1-data:
  cn2-data:
  cn3-data:
  agg-data:

networks:
  global-network:
    driver: overlay
