services:
  cn1:
    image: ghcr.io/gnosisguild/ciphernode:${TAG}
    volumes:
      - ./cn1.yaml:/home/ciphernode/.config/enclave/config.yaml:ro
      - cn1-data:/home/ciphernode/.local/share/enclave
    secrets:
      - source: secrets_cn1
        target: secrets.json
    environment:
      RUST_LOG: "info"
      AGGREGATOR: "false"
    ports:
      - 9091:9091
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
    networks:
      - global-network


  cn2:
    image: ghcr.io/gnosisguild/ciphernode:${TAG}
    depends_on:
      - cn1
    volumes:
      - ./cn2.yaml:/home/ciphernode/.config/enclave/config.yaml:ro
      - cn2-data:/home/ciphernode/.local/share/enclave
    secrets:
      - source: secrets_cn2
        target: secrets.json
    environment:
      RUST_LOG: "info"
      AGGREGATOR: "false"
    ports:
      - 9092:9092

    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
    networks:
      - global-network

  cn3:
    image: ghcr.io/gnosisguild/ciphernode:${TAG}
    depends_on:
      - cn1
    volumes:
      - ./cn3.yaml:/home/ciphernode/.config/enclave/config.yaml:ro
      - cn3-data:/home/ciphernode/.local/share/enclave
    secrets:
      - source: secrets_cn3
        target: secrets.json
    environment:
      RUST_LOG: "info"
      AGGREGATOR: "false"
    ports:
      - 9093:9093
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
    networks:
      - global-network


  aggregator:
    image: ghcr.io/gnosisguild/ciphernode:${TAG}
    depends_on:
      - cn1
    volumes:
      - ./agg.yaml:/home/ciphernode/.config/enclave/config.yaml:ro
      - agg-data:/home/ciphernode/.local/share/enclave
    secrets:
      - source: secrets_agg
        target: secrets.json
    environment:
      RUST_LOG: "info"
      AGGREGATOR: "true"
    ports:
      - 9094:9094

    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
    networks:
      - global-network

secrets:
  secrets_cn1:
    file: cn1.secrets.json
  secrets_cn2:
    file: cn2.secrets.json
  secrets_cn3:
    file: cn3.secrets.json
  secrets_agg:
    file: agg.secrets.json   

volumes:
  cn1-data:
  cn2-data:
  cn3-data:
  agg-data:

networks:
  global-network:
    driver: overlay
